const products = 
[{
    id: 0,
    type: 'Inyector',
    specification: '0445116035',
    price: 140377,
    img: './images/Inyectores/Inyector Amarok.png',
}, {
    id: 1,
    type: 'Inyector',
    specification: '0445120007',
    price: 105340,
    img: './images/Inyectores/Inyector Ford Cargo 1722.png',
},
{
    id: 2,
    type: 'Inyector',
    specification: '0414701013',
    price: 267105,
    img: './images/Inyectores/Inyector Bomba Stralis.png',
}, {
    id: 3,
    type: 'Inyector',
    specification: '0445120120',
    price: 74250,
    img: './images/Inyectores/Inyector Cummins.png',
}, {
    id: 4,
    type: 'Inyector',
    specification: '0432191442',
    price: 25430,
    img: './images/Inyectores/Inyector Mercedes benz.png',
}, {
    id: 5,
    type: 'Inyector',
    specification: '97095008292',
    price: 189211,
    img: './images/Inyectores/Inyector Toyota.png',
}, {
    id: 6,
    type: 'Bomba',
    specification: 'John Deere',
    price: 140377,
    img: './images/Inyectores/Bomba John Deere.png',
}, {
    id: 7,
    type: 'Bomba',
    specification: 'Toyota Hilux',
    price: 140377,
    img: './images/Inyectores/Bomba Toyota Hilux.png',
}, {
    id: 8,
    type: 'Bomba',
    specification: 'Amarok',
    price: 140377,
    img: './images/Inyectores/Bomba Amarok.png',
}, {
    id: 9,
    type: 'Sensor',
    specification: 'MAP',
    price: 140377,
    img: './images/Inyectores/Sensor MAP.png',
}, {
    id: 10,
    type: 'Sensor',
    specification: 'Presion de Rail',
    price: 140377,
    img: './images/Inyectores/Sensor presion de rail.png',
}, {
    id: 11,
    type: 'Sensor',
    specification: 'Flujo de Aire',
    price: 140377,
    img: './images/Inyectores/Sensor Flujo de Aire.png',
}  ]